schema_version: 1.0
tenant_id: fis
rule_deployments_by_siem:
  splunk:
  - rule_id: a123b456-c789-012d-ef34-gh567890ijkl
    enabled: true
    display_name: Detect Request Malicious Domain
  - rule_id: 91554a54-2f09-4b30-a63c-69d10babcecd
    enabled: true
    display_name: IOC Cyble Detected - Dest IPv6
  - rule_id: 2dfd0c43-f7d1-47d9-bb9d-4dab8a2649b5
    enabled: true
    display_name: IOC Cyble Detected - Inbound IPv4 by Checkpoint
  - rule_id: 9d67d3d4-4f1e-4bdd-9e2c-ac339d87b6e0
    enabled: true
    display_name: IOC Cyble Detected - Outbound IPv4 by Checkpoint
  - rule_id: 5bc9c83b-a7b7-4d9c-9703-5b759303a254
    enabled: true
    display_name: IOC Cyble Detected - Source IPv6
  - rule_id: fe1b1f0b-2f76-4e9d-a0e8-e5bac0e56961
    enabled: true
    display_name: Malicious IOC IP Address
  - rule_id: a16f64e0-33f8-470a-b0d3-b8ceb26abdaf
    enabled: true
    display_name: OpenCTI - APT IPv4 Detected by Checkpoint
  - rule_id: b27g75f1-44g9-581b-c1e4-c9def37bcgeb
    enabled: true
    display_name: OpenCTI - Attacker IPv4 Detected by Dest IP on Checkpoint
  - rule_id: c38h86g2-55h0-692c-d2f5-d0efg48cdhfc
    enabled: true
    display_name: OpenCTI - Attacker IPv4 Detected by Source IP on Checkpoint
  - rule_id: d49i97h3-66i1-703d-e3f6-e1fgh59dehgd
    enabled: true
    display_name: OpenCTI - Phishing URL Detected by Checkpoint
  - rule_id: h83m31l7-aam5-b47h-i7j0-i5jkl93hikjh
    enabled: true
    display_name: OpenCTI - Ransomware IPv4 Detected by Dest IP on Checkpoint
  - rule_id: i94n42m8-bbn6-c58h-j8k1-j6klm04iljhi
    enabled: true
    display_name: OpenCTI - Ransomware IPv4 Detected by Source IP on Checkpoint
  - rule_id: 05db2084-5ffe-45c9-b0bb-0d72796da010
    enabled: true
    display_name: Posible SCAN FTP Port (21) Per Host
  - rule_id: 760ecb29-19a2-401a-9286-8b19397b9e7d
    enabled: true
    display_name: Posible SCAN FTP Port (21) To Multiple Host
  - rule_id: 7b80b25c-c107-4523-98e9-7f011e161e16
    enabled: true
    display_name: Posible SCAN HTTP Port (80) Per Host
  - rule_id: 3dc4c061-01d8-46c6-9c81-5e65f313b5b7
    enabled: true
    display_name: Posible SCAN HTTP Port (80) To Multiple Host
  - rule_id: a1b2c3d4-e5f6-7890-ab12-cd34ef56gh78
    enabled: true
    display_name: Posible SCAN HTTPS Port (443) Per Host
  - rule_id: a2b3c4d5-e6f7-8901-ab23-cd45ef67gh89
    enabled: true
    display_name: Posible SCAN HTTPS Port (443) To Multiple Host
  - rule_id: 5ab7b8ce-ba5e-441d-80b3-e3dc538f3653
    enabled: true
    display_name: Posible SCAN SSH Port (22) Per Host
  - rule_id: 9dbd6f76-6bcc-456c-8f6b-88df38e0d232
    enabled: true
    display_name: Posible SCAN SSH Port (22) To Multiple Host
  - rule_id: d8ef70ed-4e5d-4af0-aa03-7ab3a6790d3d
    enabled: true
    display_name: Posible SCAN Telnet Port (23) Per Host
  - rule_id: 96c43ddd-3789-4916-96ec-b620bfdb4e6e
    enabled: true
    display_name: Posible SCAN Telnet Port (23) To Multiple Host
  - rule_id: 9a17ef5c-0efc-4dfd-b71d-75e3744def59
    enabled: true
    display_name: Posible SCAN TFTP Backup Port (69) Per Host
  - rule_id: a9d82e25-885d-464e-98d7-87fd12ab3fc6
    enabled: true
    display_name: Posible SCAN TFTP Backup Port (69) To Multiple Host
  - rule_id: 557f8afb-503a-4971-bd45-355b18c3a360
    enabled: true
    display_name: Single IP connects to multiple IP on Single Port
  - rule_id: a6baa0a9-f49c-48dd-8eb4-45165c93ab85
    enabled: true
    display_name: Suspected IP SCAN to FIM
