schema_version: 1.0
tenant_id: fis

rule_deployments_by_siem:
    splunk:
        - rule_id: a16f64e0-33f8-470a-b0d3-b8ceb26abdaf
          enabled: false
          display_name: "FPT - OpenCTI - APT IPv4 Detected by Checkpoint"
        - rule_id: b27g75f1-44g9-581b-c1e4-c9def37bcgeb
          enabled: false
          display_name: "FPT - OpenCTI - Attacker IPv4 Detected by Dest IP on Checkpoint"
        - rule_id: c38h86g2-55h0-692c-d2f5-d0efg48cdhfc
          enabled: false
          display_name: "FPT - OpenCTI - Attacker IPv4 Detected by Source IP on Checkpoint"
        - rule_id: d49i97h3-66i1-703d-e3f6-e1fgh59dehgd
          enabled: false
          display_name: "FPT - OpenCTI - BotnetMalware IPv4 Detected by Checkpoint"
        - rule_id: e50j08i4-77j2-814e-f4g7-f2ghi60efihe
          enabled: false
          display_name: "FPT - OpenCTI - DDOS IPv4 Detected by Checkpoint"
        - rule_id: f61k19j5-88k3-925f-g5h8-g3hij71fgjif
          enabled: false
          display_name: "FPT - OpenCTI - Honeypot IPv4 Detected by Checkpoint"
        - rule_id: g72l20k6-99l4-a36g-h6i9-h4ijk82ghjig
          enabled: false
          display_name: "FPT - OpenCTI - Phishing URL Detected by Checkpoint"
        - rule_id: h83m31l7-aam5-b47h-i7j0-i5jkl93hikjh
          enabled: false
          display_name: "FPT - OpenCTI - Ransomware IPv4 Detected by Dest IP on Checkpoint"
        - rule_id: i94n42m8-bbn6-c58h-j8k1-j6klm04iljhi
          enabled: false
          display_name: "FPT - OpenCTI - Ransomware IPv4 Detected by Source IP on Checkpoint"
        - rule_id: a1b2c3d4-e5f6-7890-ab12-cd34ef56gh78
          enabled: false
          display_name: "FPT - Posible SCAN HTTPS Port (443) Per Host"
        - rule_id: a2b3c4d5-e6f7-8901-ab23-cd45ef67gh89
          enabled: false
          display_name: "FPT - Posible SCAN HTTPS Port (443) To Multiple Host"
        - rule_id: a12b34c5-d67e-890f-g1h2-i3jklm4n5opq
          enabled: true
          display_name: "FPT - Connection to C2 detected by Checkpoint (Rule: BLOCK WEB VIRUS 2)"
        - rule_id: a123b456-c789-012d-ef34-gh567890ijkl
          enabled: true
          display_name: "FPT - Detect Request Malicious Domain"
        - rule_id: 91554a54-2f09-4b30-a63c-69d10babcecd
          enabled: true
          display_name: "FPT - IOC Cyble Detected - Dest IPv6"
        - rule_id: 2dfd0c43-f7d1-47d9-bb9d-4dab8a2649b5
          enabled: true
          display_name: "FPT - IOC Cyble Detected - Inbound IPv4 by Checkpoint"
        - rule_id: 9d67d3d4-4f1e-4bdd-9e2c-ac339d87b6e0
          enabled: true
          display_name: "FPT - IOC Cyble Detected - Outbound IPv4 by Checkpoint"
        - rule_id: 5bc9c83b-a7b7-4d9c-9703-5b759303a254
          enabled: true
          display_name: "FPT - IOC Cyble Detected - Source IPv6"